import { ArrowUpRight, CircleDollarSign, Clock3, FileText, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import Button from '../components/common/Button'
import StatusBadge from '../components/common/StatusBadge'
import { formatCurrency } from '../utils/formatCurrency'
import { getBalance, getStatus, summarizeRecords } from '../utils/calculations'

function StatCard({ label, value, note, icon: Icon, tone }) {
  return <div className="stat-card"><div className={`stat-icon stat-icon-${tone}`}><Icon size={19} /></div><div className="stat-label">{label}</div><strong className="stat-value">{value}</strong><div className="stat-note"><span className={`trend trend-${tone}`}><ArrowUpRight size={13} /> {tone === 'amber' ? 'Needs attention' : note}</span></div></div>
}

export default function Dashboard({ customers, sales }) {
  const summary = summarizeRecords(customers, sales)
  const outstandingCustomers = customers.filter((customer) => getBalance(customer) > 0).slice(0, 5)
  return <div className="dashboard-page"><section className="welcome-row"><div><span className="eyebrow">OVERVIEW</span><h2>Good morning, Ahmed</h2><p>Here&apos;s what&apos;s happening with your business today.</p></div><Button variant="secondary" icon={FileText}>Download summary</Button></section><section className="stat-grid"><StatCard label="Total customers" value="437" note="2.4% this month" icon={Users} tone="blue" /><StatCard label="Total sales" value={formatCurrency(summary.sales)} note="8.7% this month" icon={FileText} tone="teal" /><StatCard label="Amount received" value={formatCurrency(summary.received)} note="12.8% this month" icon={CircleDollarSign} tone="green" /><StatCard label="Outstanding amount" value={formatCurrency(summary.outstanding)} note="" icon={Clock3} tone="amber" /></section><div className="dashboard-grid"><section className="panel recent-panel"><div className="panel-header"><div><h3>Recent sales</h3><p>Your latest invoices and payment status</p></div><Link className="text-link" to="/sales">View all <ArrowUpRight size={14} /></Link></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Date</th><th>Total</th><th>Paid</th><th>Remaining</th><th>Status</th></tr></thead><tbody>{sales.slice(0, 5).map((sale) => <tr key={sale.id}><td><span className="invoice-id">{sale.id}</span></td><td><strong>{sale.customer}</strong></td><td>{sale.date}</td><td>{formatCurrency(sale.total)}</td><td>{formatCurrency(sale.paid)}</td><td className={sale.total - sale.paid > 0 ? 'amount-due' : ''}>{formatCurrency(sale.total - sale.paid)}</td><td><StatusBadge status={getStatus(sale.total, sale.paid)} /></td></tr>)}</tbody></table></div></section><section className="panel outstanding-panel"><div className="panel-header"><div><h3>Outstanding customers</h3><p>Accounts that need follow-up</p></div><Link className="text-link" to="/payments">View all <ArrowUpRight size={14} /></Link></div><div className="mini-list">{outstandingCustomers.map((customer) => <div className="mini-customer" key={customer.id}><div className="customer-avatar">{customer.name.split(' ').map((word) => word[0]).slice(0, 2).join('')}</div><div className="mini-customer-copy"><strong>{customer.name}</strong><span>{customer.phone}</span></div><div className="mini-customer-due"><strong>{formatCurrency(getBalance(customer))}</strong><Link to={`/customers/${customer.id}`}>View</Link></div></div>)}</div><div className="outstanding-total"><span>Total outstanding</span><strong>{formatCurrency(summary.outstanding)}</strong></div></section></div></div>
}
