import { useMemo, useState } from 'react'
import { ArrowUpRight, CheckCircle2, CircleDollarSign, CreditCard } from 'lucide-react'
import Button from '../components/common/Button'
import Modal from '../components/common/Modal'
import StatusBadge from '../components/common/StatusBadge'
import { formatCurrency } from '../utils/formatCurrency'
import { getStatus, summarizeRecords } from '../utils/calculations'

function PaymentModal({ customer, onConfirm, onClose }) {
  const [amount, setAmount] = useState('')
  const [method, setMethod] = useState('Cash')
  const [note, setNote] = useState('')
  const remaining = Math.max(0, customer.balance - Number(amount || 0))
  function submit(event) { event.preventDefault(); onConfirm(Number(amount), method, note); onClose() }
  return <Modal title="Receive payment" subtitle={`Record a payment from ${customer.name}`} onClose={onClose}><form onSubmit={submit}><div className="payment-customer"><div className="customer-avatar">{customer.name.split(' ').map((word) => word[0]).slice(0, 2).join('')}</div><div><strong>{customer.name}</strong><span>Current outstanding balance</span></div><b className="amount-due">{formatCurrency(customer.balance)}</b></div><div className="form-grid"><label>Payment amount *<input required type="number" min="1" max={customer.balance} value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Enter amount" /></label><label>Payment method<select value={method} onChange={(event) => setMethod(event.target.value)}><option>Cash</option><option>Bank transfer</option><option>Other</option></select></label><label>Optional note<textarea rows="3" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add a note about this payment" /></label></div><div className="remaining-callout"><span>Remaining after payment</span><strong className={remaining ? 'amount-due' : 'positive-text'}>{formatCurrency(remaining)}</strong></div><div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" icon={CheckCircle2}>Confirm payment</Button></div></form></Modal>
}

export default function Payments({ customers, sales, onReceivePayment }) {
  const [tab, setTab] = useState('received')
  const [selectedCustomer, setSelectedCustomer] = useState(null)
  const summary = summarizeRecords(customers, sales)
  const outstanding = useMemo(() => customers.filter((customer) => customer.totalPurchases > customer.paid).map((customer) => ({ ...customer, balance: customer.totalPurchases - customer.paid })), [customers])
  return <div className="content-page"><div className="page-heading"><div><span className="eyebrow">COLLECTIONS</span><h2>Payments</h2><p>Monitor received and outstanding customer payments.</p></div><div className="received-chip"><CircleDollarSign size={17} /><span>Received this month</span><strong>{formatCurrency(summary.received)}</strong></div></div><div className="page-tabs"><button className={tab === 'received' ? 'page-tab active' : 'page-tab'} onClick={() => setTab('received')}><CheckCircle2 size={16} /> Received / Cleared</button><button className={tab === 'outstanding' ? 'page-tab active' : 'page-tab'} onClick={() => setTab('outstanding')}><CreditCard size={16} /> Outstanding <span>{outstanding.length}</span></button></div>{tab === 'received' ? <section className="panel table-panel"><div className="table-toolbar simple"><div><h3>Received payments</h3><p>Payments recorded against customer invoices</p></div></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Invoice</th><th>Total bill</th><th>Amount received</th><th>Date</th><th>Method</th><th>Status</th></tr></thead><tbody>{sales.filter((sale) => sale.paid > 0).map((sale) => <tr key={sale.id}><td><strong>{sale.customer}</strong></td><td><span className="invoice-id">{sale.id}</span></td><td>{formatCurrency(sale.total)}</td><td className="positive-text">{formatCurrency(sale.paid)}</td><td>{sale.date}</td><td>{sale.paid === sale.total ? 'Cleared' : 'Part payment'}</td><td><StatusBadge status={getStatus(sale.total, sale.paid)} /></td></tr>)}</tbody></table></div><div className="table-total"><span>Total received</span><strong>{formatCurrency(summary.received)}</strong></div></section> : <section className="panel table-panel"><div className="table-toolbar simple"><div><h3>Outstanding accounts</h3><p>Customers with a balance still due</p></div></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Phone</th><th>Total bill</th><th>Paid</th><th>Remaining</th><th>Last payment</th><th>Action</th></tr></thead><tbody>{outstanding.map((customer) => <tr key={customer.id}><td><strong>{customer.name}</strong></td><td>{customer.phone}</td><td>{formatCurrency(customer.totalPurchases)}</td><td>{formatCurrency(customer.paid)}</td><td className="amount-due">{formatCurrency(customer.balance)}</td><td>30 Sep 2026</td><td><Button variant="small" icon={ArrowUpRight} onClick={() => setSelectedCustomer(customer)}>Receive payment</Button></td></tr>)}</tbody></table></div><div className="table-total due"><span>Total outstanding</span><strong>{formatCurrency(summary.outstanding)}</strong></div></section>}{selectedCustomer && <PaymentModal customer={selectedCustomer} onConfirm={(amount, method, note) => onReceivePayment(selectedCustomer.id, amount, method, note)} onClose={() => setSelectedCustomer(null)} />}</div>
}
