import { BarChart3, Download, FileText, Receipt, Users } from 'lucide-react'
import Button from '../components/common/Button'
import { formatCurrency } from '../utils/formatCurrency'
import { summarizeRecords } from '../utils/calculations'

export default function Reports({ customers, sales }) {
  const summary = summarizeRecords(customers, sales)
  return <div className="content-page"><div className="page-heading"><div><span className="eyebrow">BUSINESS INTELLIGENCE</span><h2>Reports</h2><p>Understand your sales and collection performance.</p></div><Button variant="secondary" icon={Download}>Export report</Button></div><section className="report-stats"><div><div className="report-icon blue"><BarChart3 size={18} /></div><span>Total sales</span><strong>{formatCurrency(summary.sales)}</strong><small>Across {sales.length} invoices</small></div><div><div className="report-icon green"><Receipt size={18} /></div><span>Total received</span><strong>{formatCurrency(summary.received)}</strong><small>Collected to date</small></div><div><div className="report-icon amber"><FileText size={18} /></div><span>Total outstanding</span><strong>{formatCurrency(summary.outstanding)}</strong><small>Needs collection</small></div><div><div className="report-icon teal"><Users size={18} /></div><span>Total customers</span><strong>437</strong><small>Active accounts</small></div></section><div className="report-grid"><section className="report-placeholder"><div className="placeholder-graphic"><BarChart3 size={28} /></div><h3>Sales report</h3><p>Review sales volume, invoice trends, and top customers by period.</p><Button variant="secondary">Open sales report</Button></section><section className="report-placeholder"><div className="placeholder-graphic green"><Receipt size={28} /></div><h3>Payment report</h3><p>Track collection activity and compare received payments over time.</p><Button variant="secondary">Open payment report</Button></section><section className="report-placeholder"><div className="placeholder-graphic amber"><FileText size={28} /></div><h3>Outstanding report</h3><p>Identify overdue accounts and prioritize your next follow-ups.</p><Button variant="secondary">Open outstanding report</Button></section></div></div>
}
